# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dummy_robot_arm_controller
    - dummy_robot_gripper

  dummy_robot_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint0_1
      - joint1_2
      - joint2_3
      - joint3_4
      - joint4_5
      - joint5_6
    action_ns: follow_joint_trajectory
    default: true
  dummy_robot_gripper:
    type: GripperCommand
    joints:
      - finger_left_pos
      - finger_right_pos
    action_ns: gripper_cmd
    default: true
